week4/timetracking/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :projects, only: [:index, :show, :new, :create] do   # 404 rather than internal server error. 
    resources :time_entries, except: [:show]
  end

  get "/", to: "site#home"    # if get routes / go to    it's actually a hash {to: "site#home"} 
  get "/contact", to: "site#contact" 


  # get "/projects" => "projects#index"

  # get "/projects/new" => "projects#new"  # has to go before projects/:id
  # get "/projects/:id" => "projects#show"

  # post "/projects" => "projects#create"

  # get "/projects/:project_id/time_entries" => "time_entries#index"

  # get "/projects/:project_id/time_entries/new" => "time_entries#new"

  # post "/projects/:project_id/time_entries" => "time_entries#create", as: :project_time_entries

  # get "/projects/:project_id/time_entries/:id/edit" => "time_entries#edit"

  # patch "/projects/:project_id/time_entries/:id" => "time_entries#update", as: :project_time_entry

  # delete "/projects/:project_id/time_entries/:id" => "time_entries#destroy"

end

week4/timetracking/app/models/car.rb
class Car < ApplicationRecord
end

week4/timetracking/app/models/project.rb
class Project < ApplicationRecord   # base class of all models  ActiveRecord::Base

  has_many :time_entries

  validates :name, presence:true, uniqueness:true, length: {maximum:50}, format: { with: /\A[a-zA-Z0-9\s]*\z/ }







  def self.clean_old

    oldest = Time.now - 1.month
    latest =  Time.now - 1.hour

    old_projects = Project.where("created_at < ? AND created_at > ?",latest, oldest)

    old_projects.destroy_all


  end




end

week4/timetracking/app/models/time_entry.rb
class TimeEntry < ApplicationRecord

  belongs_to :project

  validates :hours, presence: true, numericality: { only_integer: true }
  validates :minutes, presence: true, numericality: { only_integer: true }
  validates :date, presence:true
  validates_associated :project
  # the_entry = TimeEntry.create(
  #   hours: 1,
  #   minutes: 45,
  #   comments: "Did stuff",
  #   date: Time.now,
  #   project_id: 1
  #   )




end

week4/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index

    @project_array = Project.order(created_at:"desc")
                             .limit(10)
                             
    render "index"

  end
  def show
    @my_project = Project.find(params[:id])

    render "show"


  end

  def new

    @my_project = Project.new

    render"new"


  end

  def create
    @my_project = Project.new(
      :name => params[:project][:name],
      :description => params[:project][:description]
      )
    @my_project.save

    redirect_to "/projects/#{@my_project.id}"

  end 
end

week4/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController

  def home 

    render 'home'  # a name of view template

  end

  def controller
    render "contact"

  end

  


end

week4/timetracking/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  def index
    @my_project = Project.find(params[:project_id])
    @my_entries = @my_project.time_entries

    render "index"


  end


  def new 
    @my_project = Project.find(params[:project_id])
    @my_entry = @my_project.time_entries.new

    render "new"
  end


  def create 
    @my_project = Project.find(params[:project_id])

    @my_entry = @my_project.time_entries.new(entry_params)

    if @my_entry.save
      redirect_to "/projects/#{@my_project.id}/time_entries"
    else
      render "new"
    end


  end


  def edit
    @my_project = Project.find(params[:project_id])

    @my_entry = @my_project.time_entries.find params[:id]

    render "edit"


  end


  def update
    @my_project = Project.find_by(id: params[:project_id])

    @my_entry = @my_project.time_entries.find_by(id: params[:id])

    if @my_entry.update(entry_params)
      redirect_to action: "index", controller: "time_entries", project_id: @my_project.id
    else
      redirect_to :back
      # render "edit"
    end
  end

  def destroy
    @my_project = Project.find(params[:project_id])

    @my_entry = @my_project.time_entries.find(params[:id])

    @my_entry.destroy

    redirect_to project_time_entries_path(@my_project)

  end


  private

  def entry_params

  #   {
  #   hours: params[:time_entry][:hours],
  #   minutes: params[:time_entry][:minutes],
  #   date: params[:time_entry][:date],
  #   comments: params[:time_entry][:comments]
  #   }


    params.require(:time_entry).permit(:hours,:minutes,:date,:comments)    #require the key time_entry if not in ,then error
    # then insdie time_entry only allows these 4 inputs .

  end
end

week4/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

week4/timetracking/app/helpers/site_helper.rb
module SiteHelper
end

week4/timetracking/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

week4/timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<h1>hahaha</h1>


    <%= yield %>    

<!-- yield the html block -->

  </body>
</html>

week4/timetracking/app/views/site/contact.html.erb
	<p> ironhack@ironhack.com </p>
	<p>hahahahahaahahahah</p>

week4/timetracking/app/views/site/home.html.erb
	<h1> Welcome to this timetracking tool</h1>

	<%= render("partials/sign_up") %>
	<!-- internal -->

	<p> Ironhack powered</p>

	<!-- <img src="/assets/fargo.gif" alt="fargo image">     -->
<!-- public url -->

	<%= image_tag "fargo.gif" %>

	<a href="/contact"></a>

week4/timetracking/app/views/time_entries/edit.html.erb
<h1>Edit Time Entries</h1>


<%= render "partials/form" %>

week4/timetracking/app/views/time_entries/index.html.erb
<h1>Time Entries List</h1>









<ul>
	<% @my_entries.each do |entry| %>

		<li>

			<%= entry.hours %> h	
			<%= entry.minutes %> m -
			<%= entry.date %>


		 	<%= link_to("Edit", "/projects/#{@my_project.id}/time_entries/#{entry.id}/edit") %>
		 	<%= link_to("Delete", project_time_entry_path(@my_project,entry) , method: :delete, data: {confirm: "Are you sure?"}) %>
		</li>

	<% end %>
	


</ul>

week4/timetracking/app/views/time_entries/new.html.erb
<h1>Form</h1>



<% if @my_entry.errors.any? %>
	<ul>
		<% @my_entry.errors.full_messages.each do |error_msg| %>
			<li> <%= error_msg %></li>

		<% end %>

	</ul>
<% end %>


	
<%= form_for [@my_project, 	@my_entry] do |f| %>


	<%= f.label :hours %>
	<%= f.text_field :hours %>


	<%= f.label :minutes %>
	<%= f.text_field :minutes %>


	<%= f.label :comments %>
	<%= f.text_field :comments %>



	<%= f.label :date %>
	<%= f.date_field :date %>


	<%= f.button %>


<% end %>